@startuml
class com.bohdanbulakh.drawing_app.MainActivity {
- MenuItem? checkedToolbarMenuItem
- Menu toolbarMenu
- TextView windowTitle
-  editor
+ void onCreate(Bundle?)
+ Boolean onCreateOptionsMenu(Menu?)
+ Boolean onOptionsItemSelected(MenuItem)
- Boolean startEditor(MenuItem)
- void makeToolbarMenuItemActive(Int)
}


class com.bohdanbulakh.drawing_app.utils.CoordinateUtils$Companion {
+ Coordinates calcStartFromCenter(Coordinates,Coordinates)
+ CoordinatesPair calcCubeCoords(CoordinatesPair)
+ Array<CoordinatesPair> getCubeLinesCoords(CoordinatesPair,CoordinatesPair)
+ CoordinatesPair calcCircleCoords(Coordinates,Float)
}

class com.bohdanbulakh.drawing_app.utils.CoordinateUtils {
}
abstract class com.bohdanbulakh.drawing_app.shapes.Shape {
+ CoordinatesPair coords
+ Boolean gumStyle
+ Paint gumStylePaint
+ Paint paint
}

class com.bohdanbulakh.drawing_app.MyEditor {
-  arraySize
-  shapes
- ShapeInterface currentShape
+ void start(ShapeInterface)
+ void onPaint(Canvas)
+ void onLBdown(Coordinates)
+ void onMouseMove(Coordinates)
+ void onLBup()
}


class com.bohdanbulakh.drawing_app.shapes.RectShape {
- Coordinates center
+ <<Create>> RectShape()
+ void show(Canvas)
+ void set(CoordinatesPair)
+ void writeEnd(Coordinates)
+ void getShape()
}


class com.bohdanbulakh.drawing_app.utils.ArrayUtils$Companion {
+ void addItem(Array<T?>,T)
+ T getLastItem(Array<T>)
+ void removeFirst(Array<T?>)
}

class com.bohdanbulakh.drawing_app.utils.ArrayUtils {
}
class com.bohdanbulakh.drawing_app.Canvas {
- MyEditor editor
+ <<Create>> Canvas(Context,AttributeSet)
+ void setEditor(MyEditor)
+ void onDraw(Canvas)
+ Boolean onTouchEvent(MotionEvent?)
}


class com.bohdanbulakh.drawing_app.shapes.LineShape {
+ <<Create>> LineShape()
}

class com.bohdanbulakh.drawing_app.shapes.PointShape {
+ <<Create>> PointShape()
+ void show(Canvas)
+ void getShape()
}

class com.bohdanbulakh.drawing_app.shapes.LineOOShape {
+ <<Create>> LineOOShape()
+ void show(Canvas)
+ void getShape()
}

interface com.bohdanbulakh.drawing_app.shapes.interfaces.LineInterface {
+ void show(Canvas)
+ ShapeInterface getShape()
}

class com.bohdanbulakh.drawing_app.shapes.CubeShape {
+ <<Create>> CubeShape()
+ void show(Canvas)
+ void getShape()
}

class com.bohdanbulakh.drawing_app.MenuItems$Companion {
+ MenuItems? getShape(Int)
}

enum com.bohdanbulakh.drawing_app.MenuItems {
+  POINT
+  LINE
+  LINE_WITH_POINTS
+  RECT
+  CUBE
+  ELLIPSE
+  ids
+ <<Create>> MenuItems(Int,Int,String)
}


class com.bohdanbulakh.drawing_app.shapes.EllipseShape {
+  fillPaint
+ <<Create>> EllipseShape()
+ void show(Canvas)
+ void getShape()
}


interface com.bohdanbulakh.drawing_app.shapes.interfaces.ShapeInterface {
+ CoordinatesPair coords
+ Boolean gumStyle
+ Paint gumStylePaint
+ Paint paint
+ void set(CoordinatesPair)
+ void writeEnd(Coordinates)
+ void show(Canvas)
+ ShapeInterface getShape()
}


class com.bohdanbulakh.drawing_app.Coordinates {
+ <<Create>> Coordinates(Float,Float)
}

class com.bohdanbulakh.drawing_app.CoordinatesPair {
+ <<Create>> CoordinatesPair(Coordinates,Coordinates)
}



androidx.appcompat.app.AppCompatActivity <|-- com.bohdanbulakh.drawing_app.MainActivity
com.bohdanbulakh.drawing_app.utils.CoordinateUtils +.. com.bohdanbulakh.drawing_app.utils.CoordinateUtils$Companion
com.bohdanbulakh.drawing_app.shapes.interfaces.ShapeInterface <|.. com.bohdanbulakh.drawing_app.shapes.Shape
com.bohdanbulakh.drawing_app.shapes.Shape <|-- com.bohdanbulakh.drawing_app.shapes.RectShape
com.bohdanbulakh.drawing_app.utils.ArrayUtils +.. com.bohdanbulakh.drawing_app.utils.ArrayUtils$Companion
android.view.View <|-- com.bohdanbulakh.drawing_app.Canvas
com.bohdanbulakh.drawing_app.shapes.Shape <|-- com.bohdanbulakh.drawing_app.shapes.LineShape
com.bohdanbulakh.drawing_app.shapes.interfaces.LineInterface <|.. com.bohdanbulakh.drawing_app.shapes.LineShape
com.bohdanbulakh.drawing_app.shapes.Shape <|-- com.bohdanbulakh.drawing_app.shapes.PointShape
com.bohdanbulakh.drawing_app.shapes.EllipseShape <|-- com.bohdanbulakh.drawing_app.shapes.LineOOShape
com.bohdanbulakh.drawing_app.shapes.interfaces.LineInterface <|.. com.bohdanbulakh.drawing_app.shapes.LineOOShape
com.bohdanbulakh.drawing_app.shapes.interfaces.ShapeInterface <|.. com.bohdanbulakh.drawing_app.shapes.interfaces.LineInterface
com.bohdanbulakh.drawing_app.shapes.RectShape <|-- com.bohdanbulakh.drawing_app.shapes.CubeShape
com.bohdanbulakh.drawing_app.shapes.interfaces.LineInterface <|.. com.bohdanbulakh.drawing_app.shapes.CubeShape
com.bohdanbulakh.drawing_app.MenuItems +.. com.bohdanbulakh.drawing_app.MenuItems$Companion
com.bohdanbulakh.drawing_app.shapes.Shape <|-- com.bohdanbulakh.drawing_app.shapes.EllipseShape
@enduml